const languages = [
	{ name: "arduino", extensions: [ ".ino" ] },
	{ name: "actionscript", extensions: [ ".as" ] },
	{ name: "bash", extensions: [ ".sh", ".zsh" ] },
	{ name: "csharp", extensions: [ ".cs" ] },
	{ name: "c", extensions: [ ".c", ".h" ] },
	{ name: "cpp", extensions: [ ".cpp", ".hpp" ] },
	{ name: "cmake", extensions: [ "cmake.in" ] },
	{ name: "css", extensions: [ ".css" ] },
	{ name: "d", extensions: [ ".d" ] },
	{ name: "dos", extensions: [ ".bat", ".cmd" ] },
	{ name: "dockerfile", extensions: [ "dockerfile", "Dockerfile" ] },
	{ name: "go", extensions: [ ".go" ] },
	{ name: "gradle", extensions: [ ".gradle" ] },
	{ name: "xml", extensions: [ ".xml", ".html", ".xhtml", ".rss", ".atom", ".xjb", ".xsd", ".xsl", ".plist", ".svg" ] },
	{ name: "haskell", extensions: [ ".hs" ] },
	{ name: "ini", extensions: [ ".ini", ".toml" ] },
	{ name: "json", extensions: [ ".json" ] },
	{ name: "java", extensions: [ ".java", ".jsp" ] },
	{ name: "javascript", extensions: [ ".js", ".jsx" ] },
	{ name: "kotlin", extensions: [ ".kt" ] },
	{ name: "lua", extensions: [ ".lua" ] },
	{ name: "makefile", extensions: [ "makefile", "Makefile" ] },
	{ name: "markdown", extensions: [ ".md" ] },
	{ name: "objectivec", extensions: [ ".m", ".mm", ".M" ] },
	{ name: "php", extensions: [ ".php" ] },
	{ name: "perl", extensions: [ ".pl", ".pm" ] },
	{ name: "plaintext", extensions: [ ".txt" ] },
	{ name: "pgsql", extensions: [ ".pgsql" ] },
	{ name: "powershell", extensions: [ ".ps", ".ps1" ] },
	{ name: "python", extensions: [ ".py" ] },
	{ name: "ruby", extensions: [ ".rb" ] },
	{ name: "rust", extensions: [ ".rs" ] },
	{ name: "scss", extensions: [ ".scss" ] },
	{ name: "sql", extensions: [ ".sql" ] },
	{ name: "swift", extensions: [ ".swift" ] },
	{ name: "typescript", extensions: [ ".ts" ] },
	{ name: "vbnet", extensions: [ ".vb" ] },
	{ name: "vba", extensions: [ ".vba" ] },
	{ name: "vbscript", extensions: [ ".vbs" ] },
	{ name: "vim", extensions: [ ".vim" ] },
	{ name: "yml", extensions: [ ".yml" ] }
];

export default languages;