image: node:latest

cache:
    paths:
        - node_modules/

test:
    before_script:
        - apt-get update -qq && apt-get install -y -qq git libpcre3 libpcre2-posix0 libkrb5-3 libk5crypto3 libcom-err2 libssl1.1 libssl-dev
    script:
        - yarn install
        - yarn test